version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2
  auto: artsy/auto@1.2.0

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore:
                - master
          requires:
            - yarn/update-cache
